### ISSUE TITLE
More info on configuration

### ISSUE THREAD

**Issue by simobgl** [Sam-Izdat/pogo#1]
Hi, this is a very nice and useful project, many thanks.
I think the config file needs some clarification, without  assuming too much knowledge of GNU Gettext.
For example the project_filename field needs some info.
It this used both from the pogo executable to fetch and generate the translations and from the lib when asking to correctly identify the translation domain and file... is this correct?

**Comment by Sam-Izdat** [comment]
Right now, project_filename only defines the base filename you want assigned to the .pot and .po files covered by your POGO.toml's scope; it serves no other purpose and it was meant to help group and organize catalogs, particularly for larger applications, where stuff like "my_app.pot" or "translation.pot" (or some other assumed default) would be rather frustrating.

The wording is pretty confusing here. To be clear, the setting can be anything arbitrary, so long as it's a valid filename. An application might have two or more pogo "projects" or sets of catalogs, such as:

```
project_name        = "My Application User Control Panel"
project_filename    = "my_app_user_cp"
```

and

```
project_name        = "My Application Administrator Control Panel"
project_filename    = "my_app_admin_cp"
```

This way, if you need to pass the files between translators, it should be obvious what they are without looking at the contents.

So yes, it's used as the base filename both by the CLI utility when writing out your catalogs and by the library when looking for .mo files to read the messages from. Thanks for the feedback.

 Leaving this open to improve docs.

**Comment by simobgl** [comment]
Ok, this is clear. Also, there is a way not to have the built pogo executable in the same dir as the template files? Sorry for asking questions here, is there any other way I can reach you... or maybe this is the right place :-).

**Comment by Sam-Izdat** [comment]
This is totally fine and I appreciate the feedback. 

The pogo CLI executable should not need to be moved anywhere so long as it was installed to `GOBIN` (probably `GOPATH/bin`) and the `GOBIN` environment variable has been set and added to your system/user `PATH`. If those environment variables are there just run `go install` in the pogo directory or nuke it and `go get` it again. That should make the binary accessible globally.

**Comment by simobgl** [comment]
Never used GOBIN, but this is clear now, just need to have the pogo bin in bash path (either via GOBIN or other systems) and then I can use it to extract strings from the sources and templates, fine.
Also, am I speculating on how much does it takes to obtain a new translator for each route, it they can be safely created once per language and then shared amongst handlers, and also if it's possible to pass a &T instead of T in the templates execution contexts. Many thanks for answering so quickly, this really helps.

**Comment by Sam-Izdat** [comment]
I haven't done any benchmarking, but they should be pretty cheap and zippy for most use cases, especially compared to, say, PHP's alternative. I intended for translators to be evanescent and disposable. Go is all pass-by-value and the catalogs should be getting cached when loaded once, so I doubt you'd get much performance benefit from trying to hang on as long as possible or passing addresses.  If it's REST, I would just spawn a new one (or several) each request, in the request flow itself. But again, I just haven't tested enough to say for sure. I may well have completely fucked something up in terms of efficiency.

**Comment by simobgl** [comment]
Ok, I'll pass you profiling info once it's done, could be useful. Your package is working perfectly.

**Comment by Sam-Izdat** [comment]
Good to hear. Feel free to open other issues.

**Comment by Sam-Izdat** [comment]
@joegalaxy71 - if you get around to doing that profiling, would you mind opening a separate issue for performance, whenever you get a chance? I looked over the code again and I might have some optimizations in mind without changing up the API. I'm tied up for the next few days but when I get back I'd like to push out a new release with the improvements you suggested.

**Comment by Sam-Izdat** [comment]
I've tried to improve the documentation to make this point a little clearer in 9547c8770daa649ae916e8177709c4273730e550. The docs are still awful, but I figure we can just open new issues case-by-case.
